"""Bot configuration variables."""
from os import getenv, path
from dotenv import load_dotenv

BASE_DIR = path.abspath(path.dirname(__file__))
load_dotenv(path.join(BASE_DIR, '.env'))

# Environment
ENVIRONMENT = getenv('ENVIRONMENT')

# Chatango rooms
CHATANGO_TEST_ROOM = getenv('CHATANGO_TEST_ROOM')
CHATANGO_ACLEE_ROOM = getenv('CHATANGO_ACLEE_ROOM')
CHATANGO_BLAB_ROOM = getenv('CHATANGO_BLAB_ROOM')
CHATANGO_SIXERS_ROOM = getenv('CHATANGO_SIXERS_ROOM')
CHATANGO_EAGLES_ROOM = getenv('CHATANGO_EAGLES_ROOM')
CHATANGO_PHILLIES_ROOM = getenv('CHATANGO_PHILLIES_ROOM')
CHATANGO_NFL_ROOM = getenv('CHATANGO_NFL_ROOM')
CHATANGO_OBI_ROOM = getenv('CHATANGO_OBI_ROOM')
CHATANGO_DUBS_ROOM = getenv('CHATANGO_DUBS_ROOM')
CHATANGO_ROOMS = [CHATANGO_TEST_ROOM,
                  CHATANGO_ACLEE_ROOM,
                  # CHATANGO_SIXERS_ROOM,
                  # CHATANGO_PHILLIES_ROOM,
                  # CHATANGO_EAGLES_ROOM,
                  # CHATANGO_NFL_ROOM,
                  CHATANGO_OBI_ROOM,
                  ]

# Chatango credentials
CHATANGO_USERNAME = getenv('CHATANGO_USERNAME')
CHATANGO_PASSWORD = getenv('CHATANGO_PASSWORD')

# Database
DATABASE_URI = getenv('DATABASE_URI')
DATABASE_COMMANDS_TABLE = getenv('DATABASE_COMMANDS_TABLE')
DATABASE_WEATHER_TABLE = getenv('DATABASE_WEATHER_TABLE')
DATABASE_ARGS = {'ssl': {'ca': f'{BASE_DIR}/creds/ca-certificate.crt'}}

# Google Cloud
GOOGLE_broiestbot_CREDENTIALS = 'gcloud.json'
GOOGLE_BUCKET_NAME = getenv('GOOGLE_BUCKET_NAME')
GOOGLE_BUCKET_URL = getenv('GOOGLE_BUCKET_URL')

# Giphy
GIPHY_API_KEY = getenv('GIPHY_API_KEY')

# Stock
IEX_API_TOKEN = getenv('IEX_API_TOKEN')
ALPHA_VANTAGE_API = getenv('ALPHA_VANTAGE_API')

# Plotly
PLOTLY_API_KEY = getenv('PLOTLY_API_KEY')
PLOTLY_USERNAME = getenv('PLOTLY_USERNAME')

# Weather
WEATHERSTACK_API_KEY = getenv('WEATHERSTACK_API_KEY')

# Email
GMAIL_EMAIL = getenv('GMAIL_EMAIL')
GMAIL_PASSWORD = getenv('GMAIL_PASSWORD')

# Twilio
TWILIO_SENDER_PHONE = getenv('TWILIO_SENDER_PHONE')
TWILIO_RECIPIENT_PHONE = getenv('TWILIO_RECIPIENT_PHONE')
TWILIO_AUTH_TOKEN = getenv('TWILIO_AUTH_TOKEN')
TWILIO_ACCOUNT_SID = getenv('TWILIO_ACCOUNT_SID')
