[tool.poetry]
name = "broiestbot"
version = "0.1.0"
description = "Chatbot for the Chatango messaging platform."
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/toddbirchard/broiestbot/"
repository = "https://github.com/toddbirchard/broiestbot/"
documentation = "https://github.com/toddbirchard/broiestbot/"
keywords = [
    "Chatbot",
    "Chat",
    "Chatango",
    "Bot",
    "Python",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"
pandas = "*"
sqlalchemy = "*"
pymysql = "*"
google-cloud-storage = "*"
loguru = "*"
plotly = "*"
chart-studio = "*"
emoji = "*"
bs4 = "*"
wikipedia-api = "*"
imdbpy = "*"
simplejson = "*"
ipdata = "*"
boto = "*"
botocore = "*"
praw = "*"
ddtrace = "*"
uWSGI = "*"
python-dotenv = "*"
twilio = "^6.47.0"
datadog = "^0.39.0"
lyricsgenius = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "*"
black = "^20.8b1"
isort = "^5.8"

[tool.poetry.scripts]
run = "broiestbot:init_bot"

[tool.poetry.urls]
issues = "https://github.com/toddbirchard/broiestbot/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

