version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run: echo 'hello world'
      - run:
          name: Start pipenv shell
          command: 'pipenv shell'
      - run:
          name: Update dependencies
          command: 'pipenv update'
